from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / "files"
WIN_ICON_PATH = FILES_DIR / "calc_icon.jfif"

BIG_FONT = 40
MEDIUM_FONT = 24
SMALL_FONT = 19
TEXT_MARGIN = 10
MINIMUM_WIDTH = 300

# Colors
PRIMARY_COLOR = "#1e81b0"
DARKER_PRIMARY_COLOR = "#16658a"
DARKEST_PRIMARY_COLOR = "#115270"
