services:
  mysql_100:
    env_file:
      - ./.env
    image: mysql/mysql-server:latest
    container_name: mysql_100-project-banco_de_dados
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
    - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - TZ: America/Sao_Paulo
    